name: GitHub Star to SNS
on:
  schedule:
    # 15分ごとに実行
    - cron: '0/15 * * * *'
  workflow_dispatch:
jobs:
  github-star-to-sns:
    runs-on: macos-latest
    # 15分以上かかったらタイムアウト
    timeout-minutes: 15
    steps:
      # リポジトリのチェックアウト
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      # Cacheの復元
      - name: Cache Deno Deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ hashFiles('deno.lock') }}
      - name: Restore Last Execution Time Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .timestamp
          key: last-execution-time
          restore-keys: last-execution-time-
      - name: Check file exists
        id: check_file
        uses: andstor/file-existence-action@v2
        with:
          files: .timestamp
      # 現在時刻を設定
      - name: Set Current Time
        if: steps.check_file.outputs.files_exists == 'false'
        run: |
          echo "$(deno eval 'console.log(new Date().getTime())')" > .timestamp
      - name: Set Timestamp Hash
        id: set-timestamp-hash
        run: |
          echo "TIMESTAMP=${{hashFiles('.timestamp')}}" >> $GITHUB_OUTPUT
      # Denoのセットアップ
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      # Denoの実行
      - name: Deno Run
        run: deno run -A main.ts
        env:
          BLUESKY_IDENTIFIER: ${{secrets.BLUESKY_IDENTIFIER}}
          BLUESKY_PASSWORD: ${{secrets.BLUESKY_PASSWORD}}
          RSS_URL: ${{secrets.RSS_URL}}
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
          GOOGLE_AI_API_KEY: ${{secrets.GOOGLE_AI_API_KEY}}
          GEMINI_MODEL: ${{secrets.GEMINI_MODEL}}
      # Cacheの保存
      - name: Save Last Execution Time Cache
        uses: actions/cache/save@v4
        if: ${{always() && (steps.check_file.outputs.files_exists == 'false' || steps.set-timestamp-hash.outputs.TIMESTAMP != hashFiles('.timestamp'))}}
        with:
          path: |
            .timestamp
          key: last-execution-time-${{hashFiles('.timestamp')}}
